# docker-compose.yaml

services:
  v53:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "48080:8080"
    extra_hosts:
      - "${KEYCLOAK_HOSTNAME:-keycloak.test}:host-gateway"
    volumes:
      - ./app/v53:/bitnami/moodle
      - moodle_data:/bitnami/moodledata
      - ./scripts:/opt/1upmoodle/scripts:ro
    environment:
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_NAME: ${DB_NAME}
      MOODLE_DATABASE_USER: ${DB_USERNAME}
      MOODLE_DATABASE_PASSWORD: ${DB_PASSWORD}
      MOODLE_USERNAME: ${USERNAME}
      MOODLE_PASSWORD: ${PASSWORD}
      MOODLE_EMAIL: ${EMAIL}
      MOODLE_SITE_NAME: ${SITE_NAME}
      MOODLE_HOST: ${MOODLE_HOST}
      BITNAMI_DEBUG: ${DEBUG}

      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_PROTOCOL: ""

      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - db
      - mailpit
    restart: unless-stopped

  db:
    platform: linux/amd64
    image: postgres:15
    env_file:
      - .env
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - moodle_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailpit:
    platform: linux/amd64
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped

volumes:
  moodle_data:
  moodle_db_data:
